### PR TITLE
Allow running tests with native `forge`

### PR DESCRIPTION
**Pull request by klkvr**
This updates repo to simplify flow for testing EOF. GIven we don't need to patch forge, we can just ship dockerized solc binaries and allow configuring forge to use them.

This PR adds `eof-solc` file which is a simple bash script forwarding all arguments to docker container.

Currently it does not have any image configured but once we add it, running tests in this repo would be as simple as running `forge test` as foundry.toml is already configured with `eof-solc` and other EOF-related settings.

It can be already tested locally by building image via `docker build . -t eof-solc`

cc @fgimenez @mattsse let me know if this approach makes sense

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
nice!

looks like the make command no longer works because we removed the submodules @fgimenez ?

**Review by fgimenez — COMMENTED** [review]
awesome! :rocket: 

> looks like the make command no longer works because we removed the submodules @fgimenez ?

yep, also the Makefile itself is being removed, I think we should update the gh actions workflows accordingly

**Comment by klkvr** [comment]
Updated workflow, though it would still fail as we need to publish eof-solc image firat

**Comment by fgimenez** [comment]
> Updated workflow, though it would still fail as we need to publish eof-solc image firat

cool, there's another workflow to build and publish the image, we could use it too

**Comment by klkvr** [comment]
> > Updated workflow, though it would still fail as we need to publish eof-solc image firat
> 
> cool, there's another workflow to build and publish the image, we could use it too

yep, I think we don't need to update it, so can merge, publish and do a follow-up setting the specific image

**Comment by fgimenez** [comment]
@klkvr one more thing, looking at the error on CI https://github.com/paradigmxyz/forge-eof/actions/runs/10179326092/job/28154971215?pr=1 `"./eof-solc": Exec format error (os error 8)` maybe a shebang is missing?

**Comment by klkvr** [comment]
> @klkvr one more thing, looking at the error on CI https://github.com/paradigmxyz/forge-eof/actions/runs/10179326092/job/28154971215?pr=1 `"./eof-solc": Exec format error (os error 8)` maybe a shebang is missing?

ah right, updated in 689423d

**Comment by fgimenez** [comment]
cool thx, we get the docker error now https://github.com/paradigmxyz/forge-eof/actions/runs/10179551706/job/28155575113?pr=1 

btw we need to add you to maintainers, and maybe change more settings, a maintainer needs to allow running CI checks manually

**Pull request merged**
